services:
    polidog_webpay.webpay:
        class: \WebPay\WebPay
        arguments:
            - "%polidog_webpay_token"
        public: false

    polidog_webpay.method_proxy:
        class: Polidog\WebPayBundle\MethodProxy
        arguments:
            - "@polidog_webpay.webpay"
            - "@event_dispatcher"

    polidog_webpay.web_pay_api:
        class: Polidog\WebPayBundle\WebPayApi
        arguments:
            - "@polidog_webpay.method_proxy"